name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
        env:
          # Это заставляет контейнер Buildozer самому всё скачать правильно
          BUILDOZER_AUTO_ACCEPT: 1
